name: apigee-deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**.md'
    - '**.jpg'
    - '**.png'

jobs:
  apigee_deployment_job:
    runs-on: ubuntu-latest
    name: Deploy Apigee Proxy
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    
    - name: Deployment
      id: deployment
      uses: AldoMeneses86/apigeetool-deployment-action@v2.6.2
      with:
        APIGEETOOL_ERROR_STOP: "false"
        APIGEE_USERNAME: ${{ secrets.APIGEE_ID }}
        APIGEE_PASSWORD: ${{ secrets.APIGEE_PWD }}
          
    # Use the output from the `Deployment` step
    - name: Get the Apigeetool Return Code
      run: echo "Apigeetool ended with code ${{ steps.deployment.outputs.RC }}"
        
